# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4443ccd8a563bb24345d1bae348aa22b0db5f1f1e2708d9b3be4551f520198ab8515fb9686eaaaf0ba7900d4fef21626d93d917b98d257572b9984ef878bf443

test:
  secret_key_base: f61b6c754788e1d32a12ae831229e98d2dedfa51190a8850fe6ba3d8ff5712424bb09c1b2b1a5b88f571e3a92719b8251a0182a426a6bde17f80b88607c404d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
